service: dynamodb-single-table

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  TABLE_NAME: ${env:TABLE_NAME}
  REGION: ${env:REGION}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ${self:custom.REGION}
  tags:
    service: serverless-blog
  stackTags:
    application: serverlessBlog

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:*:*:table/${self:custom.TABLE_NAME}"
        - "arn:aws:dynamodb:*:*:table/${self:custom.TABLE_NAME}/index/*"

functions:
  createUser:
    handler: functions/createUser.handler
    memorySize: 128
    events:
      - http:
          path: user
          method: post
          cors: true
  createOrder:
    handler: functions/createOrder.handler
    memorySize: 128
    events:
      - http:
          path: user/{userId}/order
          method: post
          cors: true
  userOrder:
    handler: functions/userOrder.handler
    memorySize: 128
    events:
      - http:
          path: user/{userId}
          method: get
          cors: true
resources:
  - ${file(resources/dynamodb-table.yml)}