service: dynamodb-single-table

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  TABLE_NAME: ${env:TABLE_NAME}
  REGION: ${env:REGION}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ${self:custom.REGION}
  tags:
    service: serverless-blog
  stackTags:
    application: serverlessBlog

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:*:*:table/${self:custom.TABLE_NAME}"
        - "arn:aws:dynamodb:*:*:table/${self:custom.TABLE_NAME}/index/*"

functions:
  createArticle:
    handler: functions/createArticle.handler
    memorySize: 128
    events:
      - http:
          path: article
          method: post
          cors: true
  commentArticle:
    handler: functions/commentArticle.handler
    memorySize: 128
    events:
      - http:
          path: article/{articleId}/comment
          method: post
          cors: true
  getArticle:
    handler: functions/getArticle.handler
    memorySize: 128
    events:
      - http:
          path: article/{articleId}
          method: get
          cors: true
  userArticle:
    handler: functions/userArticle.handler
    memorySize: 128
    events:
      - http:
          path: user/{userId}/article
          method: get
          cors: true
  listArticle:
    handler: functions/listArticle.handler
    memorySize: 128
    events:
      - http:
          path: article
          method: get
          cors: true
  getComment:
    handler: functions/getComment.handler
    memorySize: 128
    events:
      - http:
          path: comment/{commentId}
          method: get
          cors: true
  listComment:
    handler: functions/listComment.handler
    memorySize: 128
    events:
      - http:
          path: article/{articleId}/comment
          method: get
          cors: true
  userComment:
    handler: functions/userComment.handler
    memorySize: 128
    events:
      - http:
          path: user/{userId}/comment
          method: get
          cors: true

resources:
  - ${file(resources/dynamodb-table.yml)}